[package]
name = "chord_composer"
version = "0.2.5"
authors = ["cj <unsignedbytebite@gmail.com>"]
edition = "2018"

[features]
eng = []
pt = []
zhn = []
no-audio = []

[dependencies]
rodio = "*"
stopwatch = "*"
serde = "*"
serde_yaml = "*"
serde_derive = "*"
clap = "*"
ghakuf = "*"
rand = "*"
music-timer = "*"
