[package]
name = "chord_composer"
version = "0.2.6"
authors = ["cj <unsignedbytebite@gmail.com>"]
edition = "2018"

[features]
default=["with-sound"]
with-sound = ["rodio"]

[dependencies]
rodio = {version ="*", optional = true} 
stopwatch = "*"
serde = "*"
serde_yaml = "*"
serde_derive = "*"
ghakuf = "*"
rand = "*"
music-timer = "*"
