name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose    
    - name: Build zhn
      run: cargo build --verbose --features zhn
    - name: Run tests
      run: cargo test --verbose
    - name: Build pt
      run: cargo build --verbose --features pt
    - name: Run tests
      run: cargo test --verbose
