name: Rust

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    # - name: Install dependencies
    #   run: sudo apt-get install libsdl2-dev
    - uses: actions/checkout@v1
    - name: Test
      run: cargo test --release --no-default-features
