name: Rust

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    #- name: Install dependencies
    #  run: sudo apt-get install libsdl2-dev
    - uses: actions/checkout@v1
    - name: Release Build
      run: cargo build --release
    - name: Test (eng)
      run: cargo build --verbose --features no-audio
    - name: Test (zhn)
      run: cargo build --verbose --features "zhn no-audio"
    - name: Test (pt)
      run: cargo build --verbose --features "pt no-audio"
